#!/bin/bash

# Perform tests to determine which OS this script is running in
which pacman > /dev/null 2> /dev/null
TEST_ARCH=$?
which apt-get > /dev/null 2> /dev/null
TEST_DEBIAN=$?

# Run the appropriate script
if [ $TEST_ARCH -eq 0 ]; then
	echo "You are running Arch Linux."
	echo "Running ./setup-arch..."
	./setup-arch	
elif [ $TEST_DEBIAN -eq 0 ]; then
	echo "You are running Debian Linux."
	echo "Running ./setup-debian..."
	./setup-debian
else
	echo "ERROR: Script cannot identify which OS you are running."
	echo "Please fix this script and run it again."
	exit 1
fi
