# enable color support of ls
alias ls='ls -Gp'

# rsync for itunes
# usage: jsync sourcedir targetdir
alias jsync='rsync -av --delete'

# webserver for basic website design
# usage: webserver
alias webserver='echo "Staring web server on port 8881..."; python -m SimpleHTTPServer 8881'

# run iperf with a known, public iperf server
alias jperf='iperf -c iperf.switchnap.com'

# test bandwidth speed
alias jdownload='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'

# transposit
alias transposit='cd ~/Documents/work ; source venv/bin/activate ; . .transposit_aliases ; cd transposit'

# Mount my ZFS iTunes
alias import-zack='sudo zpool import zack'

# Unmount my ZFS iTunes
alias export-zack='sudo zpool export zack'
