-bap // blank-lines-after-procedures
-bbb // blank-lines-before-block-comments
-blf // braces-after-func-def-line
-br // braces-on-if-line
-brs // braces-on-struct-decl-line
-linux
-lp // continue-at-parentheses
-nbfda // dont-break-function-decl-args
-nce // dont-cuddle-else
-nut // no tabs
-saf // space-after-for
-sai // space-after-if
-saw // space-after-while
-sob // swallow-optional-blank-lines
